#!/bin/sh
test "$(whoami)" != "root" && exec sudo -n -E "$0" "$@"

if [ -z "$VERSION" ]; then
	echo "VERSION environment variable not set"
	exit 1
fi

set -e
TMP=/tmp
FILES="$TMP/files"
TOOLS="$TMP/tools"
BUNDLE="$TMP/bundle"
IMAGE="$TMP/coreos.bin"
SIZE=9G
PATH="$TOOLS:$PATH"

aws_tools() {
	cp "$FILES/sources.list" /etc/apt/sources.list
	apt-get update -y
	apt-get install -y ec2-api-tools ec2-ami-tools
}

coreos_tools() {
	tar -xf "$FILES/tools.tar.xz" -C "$(dirname "$TOOLS")"
}

image_create() {
	# usage: image_create
	local lo=$(losetup -f)
	local install="$TMP/coreos-install"
	mkdir -p "$BUNDLE"
	truncate -s "$SIZE" "$IMAGE"
	losetup "$lo" "$IMAGE"
	wget https://raw.github.com/coreos/init/master/bin/coreos-install -O "$install"
	bash "$install" -o ami -d "$lo" -V "$VERSION"
	losetup -d "$lo"
}

echo ">> Installing AWS tools..."
aws_tools

echo ">> Installing CoreOS tools..."
coreos_tools

echo ">> Creating image..."
image_create
