#!/bin/sh
DEVICE=/dev/xvdb
PARTITION="${DEVICE}1"
echo "Creating /var on $DEVICE ..."

set -e
test -b "$DEVICE" || exit 0

cgpt create "$DEVICE"
cgpt add -i 1 -b 4096 -s 2097152 -t linux-data -l VAR "$DEVICE"
partx -a "$DEVICE"
cgpt resize "$PARTITION"
/usr/sbin/mkfs.btrfs -L VAR "$PARTITION"
